### ISSUE TITLE
any chance to get ASCIImath syntax working?

### ISSUE THREAD

**Issue by candardo** [liffiton/dokuwiki-plugin-mathjax#25]
I'd like to migrate all the math in my wikis from ASCIImath (asciimathml plugin) to mathjax in order to get a better compatibility across browsers. Since MathJax can handle asciimath syntax that should be possible without converting all my formulas, but I can't get  it to work.

What I've done:
- installed the mathjax plugin
- disabled the asciimath plugin
- typed some stuff using the default delimiter `$` or `$$`
- typed some stuff using the backtick (`` ` ``) delimiter
- typed some stuff using the backtick (`` ` ``) delimiter inside default (`$`) delimiters

What I expected: math parsed with asciimath syntax (same result as with the asciimathml plugin)
What I got (see attached image): no math at all or wrong parsiong (math as tex syntax)

Is there some way to use asciimath syntax with the mathjax plugin?

Thanks!

![asciimath](https://cloud.githubusercontent.com/assets/6369278/14060235/5cc6e932-f35e-11e5-90d2-a9a62afd3a32.png)

**Comment by liffiton** [comment]
The default configuration of the plugin does not load the AsciiMath input extension.  You should be able to enable it using a different [configuration file](https://mathjax.readthedocs.org/en/latest/config-files.html).

Try changing the the `plugin»mathjax»url` configuration option to use `TeX-MML-AM_CHTML` in place of its default `TeX-AMS_HTML`.  The complete URL would then be `//cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML`.

You may need or want to change some [AsciiMath-specific](https://mathjax.readthedocs.org/en/latest/options/asciimath2jax.html#configure-asciimath2jax) settings as well.

Let me know if that works.  If so, I'll add some notes to the plugin documentation page to help others with the same issue.

**Comment by candardo** [comment]
It works!
Great, now I can use both TeX and AsciiMath syntax and migration is just a matter of replacing `$$` delimiters with backticks.

One thing I noted: formulas are bigger in size when rendered with mathjax (not a problem for me).

**Comment by liffiton** [comment]
Great.  I'll update the documentation.
