### ISSUE TITLE
Mathjax display overlays onto table of contents.

### ISSUE THREAD

**Issue by russkel** [liffiton/dokuwiki-plugin-mathjax#26]
Hi,

I have noticed the plugin seems to conflict with the table of contents div, see screenshot:

![screen shot 2016-03-28 at 12 37 56 pm](https://cloud.githubusercontent.com/assets/1073606/14069174/0446379c-f4e2-11e5-9039-6c52a82ad043.png)

You are unable to click the links in the ToC under the mathjax display div. If I was competent in CSS I'd provide a patch, but alas.

Russ

**Comment by liffiton** [comment]
It looks like an easy workaround for this is to switch to a different renderer.  Right click on any math in the page, and select "Math Settings > Math Renderer > Common HTML".  This setting should persist (and in my tests it even applies across sites... somehow).

The Common HTML renderer is newer and faster, as well, so I've been considering switching the plugin's default configuration over to use it, anyway.  I'll leave this issue open until either I make that switch or find another fix.  Please let me know if the workaround works for you, though.

**Comment by russkel** [comment]
Excellent. Thanks for the help.
