### ISSUE TITLE
mathjax cdn will be stop at 30 april

### ISSUE THREAD

**Issue by jehos** [liffiton/dokuwiki-plugin-mathjax#28]
SEE: https://www.mathjax.org/cdn-shutting-down/

The default value of the plugin will cause problems.
plugin should provide local / alternative host option menu ...

**Comment by jehos** [comment]
oh. sorry. I didn't check default value of the plugin.

**Comment by liffiton** [comment]
No problem.  I only changed it recently anyway.  Thanks for contributing!
