### ISSUE TITLE
Using ampersand cause error

### ISSUE THREAD

**Issue by logongas** [liffiton/dokuwiki-plugin-mathjax#40]
The formula with a ampersand:

`$$ a &= 1 \\ b &=1 $$`

cause a error.

Version Dokuwiki: Release 2020-07-29 "Hogfather"
Plugin version: 2021-05-23

**Comment by liffiton** [comment]
I don't think that's valid TeX inside the `$$` environment.  You can use the AMSMath `align` environment, though:

```
\begin{align}
a &= 1 \\ b &=1
\end{align}
```

That should work.

**Comment by logongas** [comment]
Thank you very much, that's how it worked.
