### ISSUE TITLE
Latest update degrades mark-down

### ISSUE THREAD

**Issue by jasonfharris** [liffiton/dokuwiki-plugin-mathjax#41]
Hi,

I use the plugin [markdowku](https://www.dokuwiki.org/plugin:markdowku) I find it super useful. Unfortunately after a bit of tracking stuff down I found out the latest version of your MatJax plugin causes the quoted things like `SomeFunction` ie:

```
   `SomeFunction`
```

to render as ```    `SomeFunction` ``` instead of `SomeFunction` as markdown should.

I don't know if markdowku is actively maintained so much now but it is a fantastic plugin as is this one. It would be nice if they didn't conflict!

Thanks!
   Jason

**Comment by liffiton** [comment]
I added some support for asciimath, which uses the same backtick delimiter.  I think I can just add a configuration option to the MathJax plugin to let the user enable this if they want to use asciimath, defaulting to off, since it's probably much less common than tex.

**Comment by liffiton** [comment]
Alright, this should be fixed in fccaddf.  I'll close this, but feel free to comment or reopen if it still doesn't work after you update.

**Comment by jasonfharris** [comment]
I know my comment is late, but thanks for fixing this!

**Comment by liffiton** [comment]
You're welcome!
